# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d94550732787f8c531db2d8bfde91cccf6252198b3ee22ab7d14628d30f539934219ce4548041c85e532fe27402c3709057b73b9780689eacfe417436ba375e6

test:
  secret_key_base: f6966ef87036b8ae133428f3f1cf85e79aafdb9eb3a33958f360f075658b9b7299a893273ecccc4775b3522700c9153f5e291c8fa32e48c3b40737e0f01661d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
